// <auto-generated />
using System;
using ConsoleOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsoleOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConsoleOpsDbContext))]
    [Migration("20260825042851_AddOperatorSessions")]
    partial class AddOperatorSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConsoleOps.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<long>("ConfigurationVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("configuration_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("default_branch");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("NormalizedRepositoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_repository_name");

                    b.Property<string>("NormalizedRepositoryOwner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_repository_owner");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("repository_name");

                    b.Property<string>("RepositoryOwner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("repository_owner");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WorkflowFile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("workflow_file");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_normalized_name")
                        .HasFilter("NOT is_archived");

                    b.HasIndex("NormalizedRepositoryOwner", "NormalizedRepositoryName")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_repository")
                        .HasFilter("NOT is_archived");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("ConsoleOps.Domain.Projects.ProjectEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("application_url");

                    b.Property<string>("HealthUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("health_url");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("VersionUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("version_url");

                    b.HasKey("Id")
                        .HasName("pk_project_environments");

                    b.HasIndex("ProjectId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_project_environments_project_name");

                    b.ToTable("project_environments", (string)null);
                });

            modelBuilder.Entity("ConsoleOps.Domain.Projects.ProjectWorkflowRisk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at_utc");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("NormalizedWorkflowPath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("normalized_workflow_path");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("WorkflowPath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("workflow_path");

                    b.HasKey("Id")
                        .HasName("pk_project_workflow_risks");

                    b.HasIndex("ProjectId", "NormalizedWorkflowPath")
                        .IsUnique()
                        .HasDatabaseName("ux_project_workflow_risks_project_path");

                    b.ToTable("project_workflow_risks", (string)null);
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Authentication.OperatorSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AccessTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at_utc");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<long>("GitHubUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_user_id");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("ProtectedAccessToken")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("protected_access_token");

                    b.Property<string>("ProtectedRefreshToken")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("protected_refresh_token");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at_utc");

                    b.Property<DateTimeOffset>("SignedInAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_in_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_operator_sessions");

                    b.HasIndex("Login")
                        .HasDatabaseName("ix_operator_sessions_login");

                    b.HasIndex("RefreshTokenExpiresAtUtc")
                        .HasDatabaseName("ix_operator_sessions_refresh_expiry");

                    b.ToTable("operator_sessions", (string)null);
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Deployments.DeploymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("branch");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<long>("ExternalRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_run_id");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("result");

                    b.Property<int?>("RunNumber")
                        .HasColumnType("integer")
                        .HasColumnName("run_number");

                    b.Property<string>("RunUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("run_url");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("triggered_by");

                    b.Property<string>("WorkflowFile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("workflow_file");

                    b.Property<string>("WorkflowName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("workflow_name");

                    b.HasKey("Id")
                        .HasName("pk_deployments");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("ix_deployments_started_at");

                    b.HasIndex("ProjectId", "CommitSha")
                        .HasDatabaseName("ix_deployments_project_commit_sha");

                    b.HasIndex("ProjectId", "ExternalRunId")
                        .IsUnique()
                        .HasDatabaseName("ix_deployments_project_external_run_id");

                    b.ToTable("deployments", (string)null);
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Monitoring.DependencyHealthObservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HealthObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("health_observation_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_dependency_health_observations");

                    b.HasIndex("HealthObservationId")
                        .HasDatabaseName("ix_dependency_health_observations_health_observation_id");

                    b.ToTable("dependency_health_observations", (string)null);
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Monitoring.HealthObservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("EnvironmentKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment_kind");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_name");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<double?>("ResponseMilliseconds")
                        .HasColumnType("double precision")
                        .HasColumnName("response_milliseconds");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_health_observations");

                    b.HasIndex("ProjectId", "EnvironmentId", "ObservedAtUtc")
                        .HasDatabaseName("ix_health_observations_project_environment_observed_at");

                    b.ToTable("health_observations", (string)null);
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Monitoring.MonitoringActivityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_name");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_monitoring_activities");

                    b.HasIndex("ProjectId", "OccurredAtUtc")
                        .HasDatabaseName("ix_monitoring_activities_project_occurred_at");

                    b.ToTable("monitoring_activities", (string)null);
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Monitoring.SourceObservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset?>("CommittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at_utc");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("default_branch");

                    b.Property<string>("Failure")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("failure");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("character varying(201)")
                        .HasColumnName("repository");

                    b.Property<string>("ShortCommitSha")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("short_commit_sha");

                    b.HasKey("Id")
                        .HasName("pk_source_observations");

                    b.HasIndex("ProjectId", "ObservedAtUtc")
                        .HasDatabaseName("ix_source_observations_project_observed_at");

                    b.ToTable("source_observations", (string)null);
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Monitoring.VersionObservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Application")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("application");

                    b.Property<DateTimeOffset?>("BuiltAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("built_at_utc");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<string>("Environment")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reported_environment");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("EnvironmentKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment_kind");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_name");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<string>("Version")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_version_observations");

                    b.HasIndex("ProjectId", "EnvironmentId", "ObservedAtUtc")
                        .HasDatabaseName("ix_version_observations_project_environment_observed_at");

                    b.ToTable("version_observations", (string)null);
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Monitoring.VersionSyncObservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CommitsBehind")
                        .HasColumnType("integer")
                        .HasColumnName("commits_behind");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("EnvironmentKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment_kind");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("environment_name");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_version_sync_observations");

                    b.HasIndex("ProjectId", "EnvironmentId", "ObservedAtUtc")
                        .HasDatabaseName("ix_version_sync_observations_project_environment_observed_at");

                    b.ToTable("version_sync_observations", (string)null);
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Monitoring.WorkflowObservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("Failure")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("failure");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<string>("WorkflowFile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("workflow_file");

                    b.Property<string>("WorkflowName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("workflow_name");

                    b.HasKey("Id")
                        .HasName("pk_workflow_observations");

                    b.HasIndex("ProjectId", "ObservedAtUtc")
                        .HasDatabaseName("ix_workflow_observations_project_observed_at");

                    b.ToTable("workflow_observations", (string)null);
                });

            modelBuilder.Entity("ConsoleOps.Domain.Projects.ProjectEnvironment", b =>
                {
                    b.HasOne("ConsoleOps.Domain.Projects.Project", null)
                        .WithMany("Environments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_environments_projects_project_id");

                    b.OwnsOne("ConsoleOps.Domain.Projects.AzureLogSource", "LogSource", b1 =>
                        {
                            b1.Property<Guid>("ProjectEnvironmentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContainerAppName")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("azure_log_container_app_name");

                            b1.Property<Guid>("WorkspaceId")
                                .HasColumnType("uuid")
                                .HasColumnName("azure_log_workspace_id");

                            b1.HasKey("ProjectEnvironmentId");

                            b1.ToTable("project_environments");

                            b1.WithOwner()
                                .HasForeignKey("ProjectEnvironmentId");
                        });

                    b.Navigation("LogSource");
                });

            modelBuilder.Entity("ConsoleOps.Domain.Projects.ProjectWorkflowRisk", b =>
                {
                    b.HasOne("ConsoleOps.Domain.Projects.Project", null)
                        .WithMany("WorkflowRisks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_workflow_risks_projects_project_id");
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Deployments.DeploymentEntity", b =>
                {
                    b.HasOne("ConsoleOps.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_projects_project_id");
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Monitoring.DependencyHealthObservationEntity", b =>
                {
                    b.HasOne("ConsoleOps.Infrastructure.Persistence.Monitoring.HealthObservationEntity", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("HealthObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dependency_health_observations_health_observations_health_observation_id");
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Monitoring.HealthObservationEntity", b =>
                {
                    b.HasOne("ConsoleOps.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_health_observations_projects_project_id");
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Monitoring.MonitoringActivityEntity", b =>
                {
                    b.HasOne("ConsoleOps.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_monitoring_activities_projects_project_id");
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Monitoring.SourceObservationEntity", b =>
                {
                    b.HasOne("ConsoleOps.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_observations_projects_project_id");
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Monitoring.VersionObservationEntity", b =>
                {
                    b.HasOne("ConsoleOps.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_version_observations_projects_project_id");
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Monitoring.VersionSyncObservationEntity", b =>
                {
                    b.HasOne("ConsoleOps.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_version_sync_observations_projects_project_id");
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Monitoring.WorkflowObservationEntity", b =>
                {
                    b.HasOne("ConsoleOps.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_observations_projects_project_id");
                });

            modelBuilder.Entity("ConsoleOps.Domain.Projects.Project", b =>
                {
                    b.Navigation("Environments");

                    b.Navigation("WorkflowRisks");
                });

            modelBuilder.Entity("ConsoleOps.Infrastructure.Persistence.Monitoring.HealthObservationEntity", b =>
                {
                    b.Navigation("Dependencies");
                });
#pragma warning restore 612, 618
        }
    }
}
